### PR TITLE
Added error for attempting to geoip reserved IPs

### PR DESCRIPTION
**Pull request by dLuna**
The old code gives you 'Congo' for IPs such as 127.0.0.1 and other reserved IPs.

The new code will return an error for such a lookup.

I hope I got your odd indentation right; otherwise let me know.

Cheers,

Daniel

### CODE REVIEW

**Comment by dreid** [comment]
That indentation is very odd and this file is inconsistent about it.  Feel free to correct it and use the normal indentation for the code you're changing.

**Comment by dLuna** [comment]
I have now replaced that diff with a new version which uses the standard emacs indentation (which is the one I'd normally use).

**Comment by etrepum** [comment]
I can't merge this because it has no tests, is not backwards compatible, and I can't reproduce the problem you're reporting. Maybe this is a compatibility issue with the database you're using (which doesn't seem to be in your report).

```
1> egeoip:start().
ok
2> egeoip:lookup_pl("127.0.0.1").
[{country_code,<<>>},
 {country_code3,<<>>},
 {country_name,<<>>},
 {region,<<>>},
 {city,<<>>},
 {postal_code,<<>>},
 {latitude,601.5168},
 {longitude,601.5195},
 {area_code,0},
 {dma_code,0}]
```

**Comment by etrepum** [comment]
It looks like the indentation issue is due to a tab to space conversion with an incorrect tab width, not an intentionally stupid indentation regimen. indent-region will fix that right up, will do that.

**Comment by dLuna** [comment]
Using the database that's in the repo. I.e.:

```
git clone https://github.com/mochi/egeoip.git
cd egeoip/
make
erl -pa ebin/
1> application:start(egeoip).
ok
2> egeoip:lookup("127.0.0.1").
{ok,{geoip,"CG","COG","Congo",
       <<16>>,
       <<>>,<<>>,-27.0,133.0,0,0}}
```

Downloading the current version of GeoLiteCity.dat.gz also gives the exact same result.

It's true that this could be a db issue, but if so a lot more people than me will have that problem.

Would you rather return an empty result or an error for those ranges?  Seems like an error to me to do geoip on ip-addresses which are known to not have a location, but I can be persuaded otherwise.

Will add a few tests.

(As an aside, that latitude/longitude pair is an odd result)

**Comment by etrepum** [comment]
Reserved networks happen all the time when you're doing development, it would cause all sorts of problems (for us, anyway) if things exploded when you tested locally or on the LAN but not otherwise.

**Comment by etrepum** [comment]
It looks like my local copy has a symlink that's causing it to use a different database than the shipped GeoLiteCity.dat. Still not going to accept the pull request, but I'll use this issue to investigate the problem.

**Comment by dLuna** [comment]
After a short discussion over here, I agree with denying the pull request.

Some people could potentially geomap their internal 10.0.0.0/8 network, and that should of course be allowed.

**Comment by etrepum** [comment]
Fixed this properly.

https://github.com/mochi/egeoip/commit/fd7ab936f0ed8d46b98ea59a96deb50c4d2df86d

**Comment by dLuna** [comment]
Awesome!

**Pull request closed without merging**
