### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by gleber**
Hello

Here's a minor fix to allow IP as a tuple for egeoip:lookup/1. Since lookup/1 already uses ip2long, there is no need to disallow tuples there.

Thanks for great library!
Gleb Peregud

### CODE REVIEW

**Comment by lemenkov** [comment]
Looks good.

**Comment by gleber** [comment]
Funny part is that if I try to use tuple in old code the server will crash, which will lead to standard sasl's error_logger eat up c.a. gigabyte of memory when formatting error

**Comment by lemenkov** [comment]
You mean that this code crashes with old Erlang? This sounds pretty weird :)
I'll try it with several old OTP releases then.

Btw I added very simple unit-test - see this patch: lemenkov/egeoip@00dee3e29ad5f6c33c2f0a14fdc4dff2c958a656

**Comment by gleber** [comment]
Nope. I meant that (before my minor fix) passing a tuple to egeoip:lookup/1 would lead to egeoip worker to crash, which leads to error_logger eating up huge amount of memory when formatting the error report (when vanilla SASL is used). So no need to test it with old OTP releases :)

**Comment by lemenkov** [comment]
Wow, confirmed! I just met my good old friend, called OOM Killer.

**Pull request merged**
