### PR TITLE
added country database lookup

### PR DESCRIPTION
**Pull request by maxlapshin**
added lookup in country database, so no it is possible to deploy software with 300KB database, not 30 MB.

### CODE REVIEW

**Comment by twonds** [comment]
This does not seem to be different from #9 

Can you expand on why you need this feature? Also, tests would be nice.

**Comment by maxlapshin** [comment]
Well, you may not merge pull requests and you will end with a big and incosistent tree of useless forks.

This is required, because I don't want to deploy software with 30 megabytes of useless data. All erlyvideo package with whole erlang and its binaries takes 24 megabytes. And more 30 megabytes is city database.

**Comment by etrepum** [comment]
The code in this PR looks better than #9, so that one should probably be closed. Tests would make accepting this PR go more quickly.

**Comment by maxlapshin** [comment]
Got it.

**Comment by maxlapshin** [comment]
Tests are added.

**Comment by etrepum** [comment]
It looks like this PR needs to be rebased, according to GitHub there are conflicts (I haven't reviewed the code yet)

**Comment by maxlapshin** [comment]
I have rebased commits.

**Pull request merged**
